package window

// Placeholder data shown until the backend serves real folders and messages.
// TODO(phase-1): replace with folder.list / message.list / message.body calls.

type dummyFolder struct {
	Name   string
	Icon   string
	Unread int
}

type dummyMessage struct {
	From    string
	Subject string
	Snippet string
	Body    string
	Unread  bool
}

var dummyFolders = []dummyFolder{
	{Name: "Inbox", Icon: "mail-inbox-symbolic", Unread: 2},
	{Name: "Drafts", Icon: "document-edit-symbolic"},
	{Name: "Sent", Icon: "mail-send-symbolic"},
	{Name: "Archive", Icon: "folder-symbolic"},
	{Name: "Junk", Icon: "dialog-warning-symbolic"},
	{Name: "Trash", Icon: "user-trash-symbolic"},
}

var dummyMessages = []dummyMessage{
	{
		From:    "Malachi Mail <noreply@example.invalid>",
		Subject: "Welcome to Malachi Mail",
		Snippet: "This is placeholder content. The backend is not wired up yet.",
		Unread:  true,
		Body: "This message is generated by the UI skeleton.\n\n" +
			"Nothing here comes from a mail server. Once the backend implements " +
			"folder.list, message.list and message.body, this list will show " +
			"real, sanitised content.\n\n" +
			"Message bodies will eventually render sanitised HTML in a " +
			"JavaScript-disabled WebKitGTK view. Until then, plain text only.",
	},
	{
		From:    "Alice Example <alice@example.invalid>",
		Subject: "Re: Architecture review",
		Snippet: "Agreed on keeping sanitisation in the backend. One question about…",
		Unread:  true,
		Body: "Agreed on keeping sanitisation in the backend.\n\n" +
			"One question about the cursor pagination: is the cursor stable " +
			"across a sync that inserts older messages? We should document it.",
	},
	{
		From:    "Build Bot <ci@example.invalid>",
		Subject: "malachi: build #42 passed",
		Snippet: "All 3 packages built. 3 tests passed, 0 failed.",
		Body:    "All 3 packages built.\n3 tests passed, 0 failed.\n\n-- ci",
	},
	{
		From:    "Bob Example <bob@example.invalid>",
		Subject: "Lunch on Thursday?",
		Snippet: "Same place as last time? Let me know by tomorrow.",
		Body:    "Same place as last time? Let me know by tomorrow.\n\nBob",
	},
}
