// SPDX-FileCopyrightText: 2026 Vladislav Janeček
// SPDX-License-Identifier: GPL-3.0-or-later

package window

// Placeholder data shown until the backend serves real folders and messages.
// TODO(phase-1): replace with folder.list / message.list / message.body calls.

import (
	"time"

	"github.com/schotek/malachi/backend/pkg/api"
)

type dummyFolder struct {
	Name   string
	Icon   string
	Unread int
}

// dummyMessage mirrors the parts of api.MessageSummary the UI shows today,
// plus a body that message.body will eventually deliver.
type dummyMessage struct {
	From    api.Address
	Subject string
	Snippet string
	Date    time.Time
	Body    string
	Unread  bool
}

var dummyFolders = []dummyFolder{
	{Name: "Inbox", Icon: "mail-inbox-symbolic", Unread: 2},
	{Name: "Drafts", Icon: "document-edit-symbolic"},
	{Name: "Sent", Icon: "mail-send-symbolic"},
	{Name: "Archive", Icon: "folder-symbolic"},
	{Name: "Junk", Icon: "dialog-warning-symbolic"},
	{Name: "Trash", Icon: "user-trash-symbolic"},
}

// Dates are spread out so the list exercises every widget.FormatDate branch.
var dummyMessages = []dummyMessage{
	{
		From:    api.Address{Name: "Malachi Mail", Address: "noreply@example.invalid"},
		Subject: "Welcome to Malachi Mail",
		Snippet: "This is placeholder content. The backend is not wired up yet.",
		Date:    time.Now().Add(-2 * time.Hour),
		Unread:  true,
		Body: "This message is generated by the UI skeleton.\n\n" +
			"Nothing here comes from a mail server. Once the backend implements " +
			"folder.list, message.list and message.body, this list will show " +
			"real, sanitised content.\n\n" +
			"Message bodies will eventually render sanitised HTML in a " +
			"JavaScript-disabled WebKitGTK view. Until then, plain text only.",
	},
	{
		From:    api.Address{Name: "Alice Example", Address: "alice@example.invalid"},
		Subject: "Re: Architecture review",
		Snippet: "Agreed on keeping sanitisation in the backend. One question about…",
		Date:    time.Now().AddDate(0, 0, -1),
		Unread:  true,
		Body: "Agreed on keeping sanitisation in the backend.\n\n" +
			"One question about the cursor pagination: is the cursor stable " +
			"across a sync that inserts older messages? We should document it.",
	},
	{
		From:    api.Address{Address: "ci@example.invalid"},
		Subject: "malachi: build #42 passed",
		Snippet: "All 3 packages built. 3 tests passed, 0 failed.",
		Date:    time.Now().AddDate(0, 0, -8),
		Body:    "All 3 packages built.\n3 tests passed, 0 failed.\n\n-- ci",
	},
	{
		From:    api.Address{Name: "Bob Example", Address: "bob@example.invalid"},
		Subject: "Lunch on Thursday?",
		Snippet: "Same place as last time? Let me know by tomorrow.",
		Date:    time.Now().AddDate(-1, -1, 0),
		Body:    "Same place as last time? Let me know by tomorrow.\n\nBob",
	},
}
