// SPDX-FileCopyrightText: 2026 Vladislav Janeček
// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation
import Testing
@testable import MalachiCore

/// Writes a small Czech catalogue in the layout po2strings.py produces.
private func writeCzechLproj(into root: URL) throws {
    let lproj = root.appendingPathComponent("cs.lproj", isDirectory: true)
    try FileManager.default.createDirectory(at: lproj, withIntermediateDirectories: true)
    let strings = """
    /* Generated by po2strings.py from cs.po; do not edit. */

    "Connected" = "Připojeno";
    "Connected to malachid %s (pid %d)" = "Připojeno k malachid %@ (pid %ld)";
    "Protocol mismatch: UI %d, backend %d" = "Nesouhlasí verze protokolu: UI %ld, backend %ld";
    "folder\\U0004Inbox" = "Doručená pošta";
    "participant list separator\\U0004, " = ", ";
    "Line\\nbreak \\"quoted\\"" = "Zalomený\\nřádek \\"v uvozovkách\\"";
    "%-d %b" = "%-d. %-m.";

    """
    try strings.write(to: lproj.appendingPathComponent("Localizable.strings"), atomically: true, encoding: .utf8)
    let plurals: [String: Any] = [
        "%d message": [
            "NSStringLocalizedFormatKey": "%#@n@",
            "n": [
                "NSStringFormatSpecTypeKey": "NSStringPluralRuleType",
                "NSStringFormatValueTypeKey": "ld",
                "one": "%ld zpráva",
                "few": "%ld zprávy",
                "other": "%ld zpráv",
            ],
        ],
    ]
    let data = try PropertyListSerialization.data(fromPropertyList: plurals, format: .xml, options: 0)
    try data.write(to: lproj.appendingPathComponent("Localizable.stringsdict"))
}

private func tempRoot() throws -> URL {
    let root = FileManager.default.temporaryDirectory.appendingPathComponent("malachi-l10n-\(UUID().uuidString.prefix(8))", isDirectory: true)
    try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
    return root
}

private let infoMsgid = "Connected to malachid %s (pid %d)"

/// The process-wide `L10n.catalogue` is never reassigned here: suites run
/// in parallel and other suites (FormatTests, SyncControllerTests) expect
/// the English default. Catalogue behaviour is tested on instances.
struct LocalizationTests {
    @Test func englishFallback() {
        let en = Catalogue.english
        #expect(en.isEmpty)
        #expect(en.language == "en")
        #expect(en.translate("Connected") == "Connected")
        #expect(en.translate(infoMsgid, ["1.2", 42]) == "Connected to malachid 1.2 (pid 42)")
        #expect(en.context("folder", "Inbox") == "Inbox")
        #expect(en.plural("%d message", "%d messages", 1) == "1 message")
        #expect(en.plural("%d message", "%d messages", 2) == "2 messages")
        #expect(en.plural("%d message", "%d messages", 0) == "0 messages")
        #expect(en.plural("%d message", "%d messages", -1) == "-1 message")
    }

    @Test func globalShimDefaultsToEnglish() {
        #expect(L10n.catalogue.isEmpty)
        #expect(L10n.T("Connected") == "Connected")
        #expect(L10n.T(infoMsgid, "1.2", 42) == "Connected to malachid 1.2 (pid 42)")
        #expect(L10n.N("%d message", "%d messages", 1) == "1 message")
        #expect(L10n.N("%d message", "%d messages", 5) == "5 messages")
        #expect(L10n.C("folder", "Inbox") == "Inbox")
        #expect(L10n.C("participant list separator", ", ") == ", ")
        #expect(L10n.format("%d of %d attachments could not be saved", [1, 3]) == "1 of 3 attachments could not be saved")
        #expect(L10n.format("%.1f MiB", [1.5]) == "1.5 MiB")
        #expect(L10n.format("%.0f KiB", [12.6]) == "13 KiB")
        #expect(L10n.T("%d B", 7) == "7 B")
    }

    @Test func loadsACatalogueFromAnLproj() throws {
        let root = try tempRoot()
        defer { try? FileManager.default.removeItem(at: root) }
        try writeCzechLproj(into: root)

        #expect(Catalogue.availableLanguages(in: root) == ["cs"])
        let cs = Catalogue.load(from: root, languages: ["de", "cs", "en"])
        #expect(cs.language == "cs")
        #expect(!cs.isEmpty)
        #expect(cs.translate("Connected") == "Připojeno")
        #expect(cs.translate(infoMsgid, ["1.2", 42]) == "Připojeno k malachid 1.2 (pid 42)")
        #expect(cs.translate("Protocol mismatch: UI %d, backend %d", [1, 2]) == "Nesouhlasí verze protokolu: UI 1, backend 2")
        #expect(cs.translate("Line\nbreak \"quoted\"") == "Zalomený\nřádek \"v uvozovkách\"")
        // Missing keys fall back to the msgid, formatted from gettext syntax.
        #expect(cs.translate("Not in the catalogue") == "Not in the catalogue")
        #expect(cs.translate("%d unread", [3]) == "3 unread")
        // strftime msgids come back verbatim for Strftime.
        #expect(cs.translate("%-d %b") == "%-d. %-m.")
    }

    @Test func contextKeysUseTheEOTSeparator() throws {
        let root = try tempRoot()
        defer { try? FileManager.default.removeItem(at: root) }
        try writeCzechLproj(into: root)
        let cs = Catalogue.load(from: root, languages: ["cs"])
        #expect(Catalogue.contextKey("folder", "Inbox") == "folder\u{4}Inbox")
        #expect(cs.string("folder\u{4}Inbox") == "Doručená pošta")
        #expect(cs.context("folder", "Inbox") == "Doručená pošta")
        #expect(cs.context("participant list separator", ", ") == ", ")
        #expect(cs.context("nonexistent", "Inbox") == "Inbox")
        // The plain key is not the context key.
        #expect(cs.translate("Inbox") == "Inbox")
    }

    @Test func czechPlurals() throws {
        let root = try tempRoot()
        defer { try? FileManager.default.removeItem(at: root) }
        try writeCzechLproj(into: root)
        let cs = Catalogue.load(from: root, languages: ["cs"])
        #expect(cs.pluralForms("%d message")?.keys.sorted() == ["few", "one", "other"])
        #expect(cs.plural("%d message", "%d messages", 1) == "1 zpráva")
        #expect(cs.plural("%d message", "%d messages", 2) == "2 zprávy")
        #expect(cs.plural("%d message", "%d messages", 4) == "4 zprávy")
        #expect(cs.plural("%d message", "%d messages", 5) == "5 zpráv")
        #expect(cs.plural("%d message", "%d messages", 0) == "0 zpráv")
        // An untranslated plural uses the English rule on the msgids.
        #expect(cs.plural("%d attachment", "%d attachments", 2) == "2 attachments")
        #expect(cs.plural("%d attachment", "%d attachments", 1) == "1 attachment")
    }

    @Test func missingLanguageIsEnglish() throws {
        let root = try tempRoot()
        defer { try? FileManager.default.removeItem(at: root) }
        try writeCzechLproj(into: root)
        let none = Catalogue.load(from: root, languages: ["de", "fr"])
        #expect(none.isEmpty)
        #expect(none.language == "en")
        #expect(Catalogue.load(from: root, languages: []).isEmpty)
        // An .lproj without Localizable.strings does not count.
        try FileManager.default.createDirectory(at: root.appendingPathComponent("de.lproj"), withIntermediateDirectories: true)
        #expect(Catalogue.availableLanguages(in: root) == ["cs"])
        #expect(Catalogue.load(from: root, languages: ["de"]).isEmpty)
    }

    @Test func defaultCatalogueHonoursTheLocaleDir() throws {
        let root = try tempRoot()
        defer { try? FileManager.default.removeItem(at: root) }
        try writeCzechLproj(into: root)
        let empty = try tempRoot()
        defer { try? FileManager.default.removeItem(at: empty) }

        #expect(Catalogue.default(environment: [Catalogue.localeDirEnv: empty.path]).isEmpty)
        #expect(Catalogue.default(environment: [:]).isEmpty || !Bundle.main.resourceURL.map(Catalogue.availableLanguages(in:))!.isEmpty)
        // With one language available, the preference cannot pick anything else.
        let picked = Catalogue.default(environment: [Catalogue.localeDirEnv: root.path])
        #expect(picked.language == "cs")
        #expect(picked.translate("Connected") == "Připojeno")
    }

    /// The language the catalogue would pick: Foundation's matching of
    /// the user's languages against the available `.lproj`s (what
    /// `Catalogue.default` calls with the process preferences).
    @Test func languageMatchingFollowsFoundation() {
        let available = ["cs", "en"]
        #expect(Bundle.preferredLocalizations(from: available, forPreferences: ["cs"]).first == "cs")
        #expect(Bundle.preferredLocalizations(from: available, forPreferences: ["cs-CZ"]).first == "cs")
        #expect(Bundle.preferredLocalizations(from: available, forPreferences: ["en-GB"]).first == "en")
        #expect(Bundle.preferredLocalizations(from: available, forPreferences: ["de", "cs"]).first == "cs")
        // An unknown language yields something from the list, never nothing.
        let unknown = Bundle.preferredLocalizations(from: available, forPreferences: ["tlh"])
        #expect(!unknown.isEmpty && unknown.allSatisfy { available.contains($0) })
    }
}

/// The catalogues `make locale` generates from po/ (the counterpart of
/// TestCzechCatalogue in ui/internal/i18n), found through
/// MALACHI_LOCALE_DIR as `make test-macos` exports it. Skipped, not
/// failed, when the directory is absent.
private let generatedLocaleDir: URL? = {
    guard let dir = ProcessInfo.processInfo.environment[Catalogue.localeDirEnv], !dir.isEmpty else { return nil }
    let url = URL(fileURLWithPath: dir, isDirectory: true)
    let languages = Catalogue.availableLanguages(in: url)
    return languages.contains("cs") && languages.contains("en") ? url : nil
}()

private let generatedCatalogueHint: Comment = "run `make -C macos locale` and export MALACHI_LOCALE_DIR"

struct GeneratedLocalizationTests {
    private var cs: Catalogue { Catalogue.load(from: generatedLocaleDir!, languages: ["cs"]) }
    private var en: Catalogue { Catalogue.load(from: generatedLocaleDir!, languages: ["en"]) }

    /// 2026-09-02 15:04 in Prague, a Wednesday.
    private static let prague = TimeZone(identifier: "Europe/Prague")!
    private static let fixed: Date = {
        var cal = Calendar(identifier: .gregorian)
        cal.timeZone = prague
        return cal.date(from: DateComponents(year: 2026, month: 9, day: 2, hour: 15, minute: 4))!
    }()

    private func render(_ strftime: String, _ locale: String) -> String {
        let f = Strftime.formatter(strftime, locale: Locale(identifier: locale))
        f.timeZone = Self.prague
        return f.string(from: Self.fixed)
    }

    @Test(.enabled(if: generatedLocaleDir != nil, generatedCatalogueHint))
    func plainMsgids() {
        let cs = cs
        #expect(cs.language == "cs")
        #expect(cs.translate("Connected") == "Připojeno")
        #expect(cs.translate("Use") == "Použít")
        #expect(cs.translate("Connecting…") == "Připojování…")
        // Format arguments arrive converted (%s → %@, %d → %ld) by po2strings.
        #expect(cs.translate("Connected to malachid %s (pid %d)", ["1.2", 42]) == "Připojeno k malachid 1.2 (pid 42)")
        #expect(cs.translate("%d of %d attachments could not be saved", [1, 3]) == "1 z 3 příloh se nepodařilo uložit")
        #expect(cs.string("Syncing %s… %d %%") == "Synchronizuje se %@… %ld %%")
        #expect(cs.translate("Syncing %s… %d %%", ["Inbox", 5]) == "Synchronizuje se Inbox… 5 %")
    }

    @Test(.enabled(if: generatedLocaleDir != nil, generatedCatalogueHint))
    func contextKeys() {
        let cs = cs
        #expect(cs.context("folder", "Inbox") == "Doručená pošta")
        #expect(cs.context("folder", "Trash") == "Koš")
        #expect(cs.context("folder", "Drafts") == "Koncepty")
        #expect(cs.context("participant list separator", ", ") == ", ")
        #expect(cs.string("folder\u{4}Inbox") == "Doručená pošta")
        // English keeps the context keys too (they must resolve to the plain msgid).
        #expect(en.context("folder", "Inbox") == "Inbox")
        #expect(en.string("folder\u{4}Inbox") == "Inbox")
    }

    @Test(.enabled(if: generatedLocaleDir != nil, generatedCatalogueHint))
    func pluralForms() {
        let cs = cs
        #expect(cs.pluralForms("%d message")?.keys.sorted() == ["few", "one", "other"])
        #expect(cs.plural("%d message", "%d messages", 1) == "1 zpráva")
        #expect(cs.plural("%d message", "%d messages", 2) == "2 zprávy")
        #expect(cs.plural("%d message", "%d messages", 5) == "5 zpráv")
        #expect(cs.plural("%d unsafe element was removed from the message",
                          "%d unsafe elements were removed from the message", 3)
            == "3 nebezpečné prvky byly ze zprávy odstraněny")
        #expect(en.pluralForms("%d message")?.keys.sorted() == ["one", "other"])
        #expect(en.plural("%d message", "%d messages", 1) == "1 message")
        #expect(en.plural("%d message", "%d messages", 2) == "2 messages")
        #expect(en.plural("%d message", "%d messages", 5) == "5 messages")
    }

    @Test(.enabled(if: generatedLocaleDir != nil, generatedCatalogueHint))
    func dateMsgidsThroughStrftime() {
        let cs = cs
        // The four msgids of ui/internal/widget/format.go and their cs.po translations.
        #expect(cs.translate("%H:%M") == "%H:%M")
        #expect(cs.translate("%-d %b") == "%-d. %-m.")
        #expect(cs.translate("%Y-%m-%d") == "%-d. %-m. %Y")
        #expect(cs.translate("%a, %-d %b %Y at %H:%M") == "%a %-d. %-m. %Y v %H:%M")
        #expect(render(cs.translate("%H:%M"), "cs_CZ") == "15:04")
        #expect(render(cs.translate("%-d %b"), "cs_CZ") == "2. 9.")
        #expect(render(cs.translate("%Y-%m-%d"), "cs_CZ") == "2. 9. 2026")
        #expect(render(cs.translate("%a, %-d %b %Y at %H:%M"), "cs_CZ") == "st 2. 9. 2026 v 15:04")
        #expect(render(en.translate("%a, %-d %b %Y at %H:%M"), "en_US") == "Wed, 2 Sep 2026 at 15:04")
    }

    @Test(.enabled(if: generatedLocaleDir != nil, generatedCatalogueHint))
    func missingKeysFallBackToTheMsgid() {
        let cs = cs
        #expect(cs.translate("Not a msgid of Malachi Mail") == "Not a msgid of Malachi Mail")
        #expect(cs.translate("Not a msgid with %s", ["x"]) == "Not a msgid with x")
        #expect(cs.context("folder", "Not a folder") == "Not a folder")
        #expect(cs.plural("%d widget", "%d widgets", 2) == "2 widgets")
        #expect(cs.plural("%d widget", "%d widgets", 1) == "1 widget")
    }

    @Test(.enabled(if: generatedLocaleDir != nil, generatedCatalogueHint))
    func defaultPicksFromTheLocaleDir() {
        let picked = Catalogue.default(environment: [Catalogue.localeDirEnv: generatedLocaleDir!.path])
        #expect(!picked.isEmpty)
        #expect(["cs", "en"].contains(picked.language))
        // Either language resolves the context key, so the choice cannot break folder names.
        #expect(["Inbox", "Doručená pošta"].contains(picked.context("folder", "Inbox")))
    }
}
