// SPDX-FileCopyrightText: 2026 Vladislav Janeček
// SPDX-License-Identifier: GPL-3.0-or-later

// Windows-only: SHGetFileInfoW, the one declaration in this project not
// generated by CsWin32 (docs/windows-port.md §3.1): CsWin32 refuses it for
// an AnyCPU project (PInvoke005), because SHFILEINFOW is packed to one byte
// on 32-bit Windows. The app ships for x64 and ARM64 only, where the
// structure has its natural layout, which is what this declares; the
// caller checks for a 64-bit process first. Source-generated
// (LibraryImport), so trimming and AOT stay possible.

using System.Runtime.InteropServices;

namespace Malachi.Platform.Windows.Files;

/// <summary>The shell's SHGetFileInfoW for a 64-bit process.</summary>
internal static partial class ShellFileInfoInterop
{
    /// <summary>SHGFI_SYSICONINDEX: the icon's index in the system image list.</summary>
    public const uint SysIconIndex = 0x000004000;

    /// <summary>SHGFI_USEFILEATTRIBUTES: the name is not a file; the attributes stand for one.</summary>
    public const uint UseFileAttributes = 0x000000010;

    /// <summary>FILE_ATTRIBUTE_NORMAL.</summary>
    public const uint FileAttributeNormal = 0x00000080;

    /// <summary>SHGetFileInfoW; returns non-zero on success (the image list's handle for SHGFI_SYSICONINDEX).</summary>
    [LibraryImport("shell32.dll", EntryPoint = "SHGetFileInfoW", StringMarshalling = StringMarshalling.Utf16)]
    public static partial nuint SHGetFileInfo(string path, uint attributes, ref FileInfo info, uint size, uint flags);

    /// <summary>SHFILEINFOW in its 64-bit layout.</summary>
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public unsafe struct FileInfo
    {
        /// <summary>hIcon.</summary>
        public nint Icon;

        /// <summary>iIcon.</summary>
        public int IconIndex;

        /// <summary>dwAttributes.</summary>
        public uint Attributes;

        /// <summary>szDisplayName.</summary>
        public fixed char DisplayName[260];

        /// <summary>szTypeName.</summary>
        public fixed char TypeName[80];
    }
}
