// SPDX-FileCopyrightText: 2026 Vladislav Janeček
// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation

/// The gettext plural rules of the languages the catalogues may be
/// translated into, and the CLDR category names the .stringsdict files
/// generated by macos/scripts/po2strings.py use for each msgstr index.
///
/// The client picks the plural form itself (Catalogue in Localization.swift)
/// instead of going through a bundle, so the rule and the category table
/// must agree with the generator's `PLURAL_CATEGORIES`; an unknown
/// language falls back to the English rule, which is also gettext's default.
public enum PluralRules {
    /// The gettext plural index (`msgstr[i]`) of `n` in `language`.
    public static func index(language: String, n: Int) -> Int {
        let n = abs(n)
        switch base(language) {
        case "cs", "sk":
            return n == 1 ? 0 : (n >= 2 && n <= 4) ? 1 : 2
        case "pl":
            return n == 1 ? 0 : fewSlavic(n) ? 1 : 2
        case "ru", "uk":
            return (n % 10 == 1 && n % 100 != 11) ? 0 : fewSlavic(n) ? 1 : 2
        case "fr":
            return n > 1 ? 1 : 0
        case "ro":
            return n == 1 ? 0 : (n == 0 || (n % 100 > 0 && n % 100 < 20)) ? 1 : 2
        default:
            return n != 1 ? 1 : 0
        }
    }

    /// The CLDR category name used as the .stringsdict key for `n`.
    public static func category(language: String, n: Int) -> String {
        let table = categories(language: language)
        let i = index(language: language, n: n)
        return i < table.count ? table[i] : "other"
    }

    /// Category names in msgstr index order, as the generator writes them.
    public static func categories(language: String) -> [String] {
        switch base(language) {
        case "cs", "sk", "ro":
            return ["one", "few", "other"]
        case "pl", "ru", "uk":
            return ["one", "few", "many"]
        default:
            return ["one", "other"]
        }
    }

    /// "cs" for "cs", "cs-CZ", "cs_CZ" and "CS".
    static func base(_ language: String) -> String {
        let cut = language.firstIndex(where: { $0 == "-" || $0 == "_" }) ?? language.endIndex
        return language[..<cut].lowercased()
    }

    private static func fewSlavic(_ n: Int) -> Bool {
        n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 10 || n % 100 >= 20)
    }
}
